import { StyleSheet, StatusBar, Platform } from "react-native";

const styles = StyleSheet.create({
  screen: {},
  headerLeft: {
    flexDirection: "row",
    //width: '100%',
    //height: 20,
    //top: StatusBar.currentHeight,
    marginBottom: 15,
    //justifyContent: 'space-between',
    alignItems: "center",
  },
  headerRight: {
    flexDirection: "row",
    //width: '100%',
    //height: 20,
    //top: StatusBar.currentHeight,
    marginBottom: 15,
    //justifyContent: "center",
    alignItems: "center",
    marginRight: 20,
  },
  textHeader: {
    fontWeight: "bold",
    fontSize: 25,
    marginHorizontal: 5,
    alignSelf: "center",
  },
  iconContainer: {
    height: 40,
    width: 40,
    borderRadius: 20,
    justifyContent: "center",
    alignItems: "center",
    //backgroundColor: 'rgba(0,0,0,0.05)',
    marginHorizontal: 0,
  },
  container: {
    flex: 1,
  },
  inputContainer: {
    flex: 1,
  },
  footer: {
    flexDirection: "row",
    alignItems: "center",
    width: "100%",
    padding: 10,
  },
  textInput: {
    //bottom: 0,
    height: 40,
    flex: 1,
    marginRight: 5,
    marginLeft: 5,
    justifyContent: "center",
    alignItems: "center",
    borderColor: "transparent",
    borderWidth: 1,
    backgroundColor: "#ECECEC",
    paddingHorizontal: 10,
    color: "grey",
    borderRadius: 30,
    textAlignVertical: "top",
    fontSize: 16,
    paddingTop: Platform.OS === "ios" ? 10 : 0,
  },
  sender: {
    padding: 10,
    backgroundColor: "#D8D8D8",
    alignSelf: "flex-end",
    borderRadius: 20,
    marginRight: 15,
    marginBottom: 5,
    maxWidth: "80%",
    position: "relative",
  },
  senderText: {},
  receiver: {
    padding: 10,
    backgroundColor: "white",
    alignSelf: "flex-start",
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#ECECEC",
    marginLeft: 15,
    marginBottom: 5,
    maxWidth: "80%",
    position: "relative",
  },
  receiverText: {},
});

export default styles;
