/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_appsync_graphqlEndpoint": "https://btp7xquj3fblrkokqtghj7nmka.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cognito_identity_pool_id": "eu-central-1:9de1ac11-b25f-4357-9ec2-f57e48b115a7",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_nkX6k7VTh",
    "aws_user_pools_web_client_id": "6qfd9o2m9secku2kuagig1ha6s",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "ballermapmvp2e5fda8e36694dd8807e03dd4ddf2820151750-dev",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
